### ISSUE TITLE
How send SMS messages ?

### ISSUE THREAD

**Issue by fbourguignon** [agorapulse/grails-aws-sdk-sns#2]

**Comment by benorama** [comment]
Sorry, SMS is not implemented in this plugin, only push notifications.
But you can still access the native AWS SDK client (accessible through `amazonSNSService.client` in your grails app).
You might check AWS Documentation: 
http://docs.aws.amazon.com/sns/latest/dg/SMSMessages.html 

Any pull request is welcome :)
